<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE student [
    <!ELEMENT student (name,age, class, fees)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT class (#PCDATA)>
    <!ELEMENT fees (#PCDATA)>
]>
<student>
    <name>ali</name>
    <age>23</age>
    <class>10 grade</class>
    <fees>8000</fees>
</student>